---
version: 1.0
gsf:
  basic:
    backend: gloo
    ip_config: ip_list.txt
    verbose: false
    save_perf_results_path: null
  distill:
    textual_data_path: "/tmp/gsgnn_dt/distill_data" # textual dataset
    lm_name: DistilBertModel # optional, default to be DistilBertModel
    pre_trained_name: distilbert-base-uncased # optional, default to be null
  output:
    save_model_path: "/tmp/gsgnn_dt/checkpoints"
    save_model_frequency: 1000 # optional, default to be 1000
  hyperparam: # TODO (HZ): need to remove gnn training hyperparameters
    lm_tune_lr: 0.0001 # optional, default to be 0.0001
    num_epochs: 3 # optional, default to be 3
    batch_size: 128 # optional, default to be 128
    eval_frequency: 1000 # optional, default to be 1000
