---
# TODO (HZ): add config example with and without GNN inference.
version: 1.0
gsf:
  basic:
    backend: gloo
    ip_config: ip_list_debug.txt
    verbose: false
    save_perf_results_path: null
  distill:
    textual_data_path: "/fsx-CoreModeling/zhanhouy/home/m5gnn_dataset/distill_dev_data/query_distill_data" # textual dataset with node type name as sub-folder
    lm_name: DistilBertModel # model name for HuggingFace model
    pre_trained_name: distilbert-base-uncased # name for pre-trained parameters
  output:
    save_model_path: "/fsx-CoreModeling/zhanhouy/home/models/gsdistill_debug"
    save_model_frequency: 50 # optional, default to be 1000
  hyperparam: # TODO (HZ): need to remove gnn training hyperparameters
    lm_tune_lr: 0.0001
    num_epochs: 3
    batch_size: 16
    eval_frequency: 50
    max_global_step: 9999
